# Stoffel-solidity-SDK
#
# This Makefile orchestrates Solidity builds and Rust binding generation.

.PHONY: all build bindings clean test fmt lint check-bindings help

# Default target: build contracts and generate bindings
all: build bindings

# =============================================================================
# Build Targets
# =============================================================================

# Build Solidity contracts
build:
	@echo "Building Solidity contracts..."
	forge build

# Generate Rust bindings from contract ABIs
# Selects main contracts and interfaces, excluding tests and scripts
# Uses alloy 1.0 for compatibility with forge 1.4+
bindings: build
	@echo "Generating Rust contract bindings..."
	forge bind \
		--bindings-path ./bindings/src \
		--module \
		--alloy \
		--alloy-version "1.0" \
		--overwrite \
		--select "^(Stoffel(AccessControl|Coordinator|InputManager)|IStoffel.*)$$"
	@rm -f ./bindings/src/mod.rs
	@echo "Creating lib.rs with module exports..."
	@echo '//! Type-safe Rust bindings for Stoffel Solidity contracts.' > ./bindings/src/lib.rs
	@echo '//!' >> ./bindings/src/lib.rs
	@echo '//! Generated by `forge bind` using the Alloy framework.' >> ./bindings/src/lib.rs
	@echo '' >> ./bindings/src/lib.rs
	@echo '#![allow(clippy::all)]' >> ./bindings/src/lib.rs
	@echo '#![allow(missing_docs)]' >> ./bindings/src/lib.rs
	@echo '#![allow(rustdoc::all)]' >> ./bindings/src/lib.rs
	@echo '#![allow(unused_imports)]' >> ./bindings/src/lib.rs
	@echo '#![allow(unused_attributes)]' >> ./bindings/src/lib.rs
	@echo '' >> ./bindings/src/lib.rs
	@echo '// Generated contract bindings' >> ./bindings/src/lib.rs
	@echo 'pub mod i_stoffel_access_control;' >> ./bindings/src/lib.rs
	@echo 'pub mod i_stoffel_coordinator;' >> ./bindings/src/lib.rs
	@echo 'pub mod i_stoffel_input_manager;' >> ./bindings/src/lib.rs
	@echo 'pub mod stoffel_access_control;' >> ./bindings/src/lib.rs
	@echo 'pub mod stoffel_coordinator;' >> ./bindings/src/lib.rs
	@echo 'pub mod stoffel_input_manager;' >> ./bindings/src/lib.rs
	@echo '' >> ./bindings/src/lib.rs
	@echo '// Re-export main contract bindings' >> ./bindings/src/lib.rs
	@echo 'pub use stoffel_access_control::StoffelAccessControl;' >> ./bindings/src/lib.rs
	@echo 'pub use stoffel_coordinator::StoffelCoordinator;' >> ./bindings/src/lib.rs
	@echo 'pub use stoffel_input_manager::StoffelInputManager;' >> ./bindings/src/lib.rs
	@echo '' >> ./bindings/src/lib.rs
	@echo '/// Interface bindings for Stoffel contracts.' >> ./bindings/src/lib.rs
	@echo 'pub mod interfaces {' >> ./bindings/src/lib.rs
	@echo '    pub use crate::i_stoffel_access_control::IStoffelAccessControl;' >> ./bindings/src/lib.rs
	@echo '    pub use crate::i_stoffel_coordinator::IStoffelCoordinator;' >> ./bindings/src/lib.rs
	@echo '    pub use crate::i_stoffel_input_manager::IStoffelInputManager;' >> ./bindings/src/lib.rs
	@echo '}' >> ./bindings/src/lib.rs
	@echo '' >> ./bindings/src/lib.rs
	@echo '// Re-export commonly used types from alloy' >> ./bindings/src/lib.rs
	@echo 'pub use alloy::primitives::{Address, Bytes, FixedBytes, U256};' >> ./bindings/src/lib.rs
	@echo 'pub use alloy::sol_types::SolCall;' >> ./bindings/src/lib.rs

# Verify bindings compile
check-bindings: bindings
	@echo "Checking Rust bindings compilation..."
	cd bindings && cargo check

# =============================================================================
# Test Targets
# =============================================================================

# Run all Solidity tests
test:
	@echo "Running Solidity tests..."
	forge test

# Run tests with verbose output
test-verbose:
	forge test -vvv

# Run a single test
test-single:
	@echo "Usage: make test-single TEST=test_name"
	@test -n "$(TEST)" && forge test --match-test $(TEST) || echo "TEST variable not set"

# =============================================================================
# Code Quality
# =============================================================================

# Format Solidity code
fmt:
	@echo "Formatting Solidity..."
	forge fmt

# Check formatting (for CI)
lint:
	@echo "Checking Solidity formatting..."
	forge fmt --check

# =============================================================================
# Clean
# =============================================================================

clean:
	@echo "Cleaning build artifacts..."
	forge clean
	rm -rf bindings/target
	@echo "Cleaned all build artifacts"

# Clean only bindings
clean-bindings:
	rm -rf bindings/target
	rm -f bindings/src/*.rs
	@echo "Cleaned binding artifacts (lib.rs preserved)"

# =============================================================================
# Gas & Analysis
# =============================================================================

# Gas report
gas:
	forge test --gas-report

# Contract sizes
sizes:
	forge build --sizes

# =============================================================================
# Documentation
# =============================================================================

# Generate Solidity docs
docs:
	forge doc

# Generate Rust binding docs
docs-bindings: bindings
	cd bindings && cargo doc --open

# =============================================================================
# Help
# =============================================================================

help:
	@echo "Stoffel-solidity-SDK"
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "Build targets:"
	@echo "  all            - Build contracts and generate bindings (default)"
	@echo "  build          - Build Solidity contracts only"
	@echo "  bindings       - Generate Rust bindings from contract ABIs"
	@echo "  check-bindings - Verify bindings compile with cargo check"
	@echo ""
	@echo "Test targets:"
	@echo "  test           - Run all Solidity tests"
	@echo "  test-verbose   - Run tests with verbose output"
	@echo "  test-single    - Run single test (TEST=test_name)"
	@echo ""
	@echo "Code quality:"
	@echo "  fmt            - Format Solidity code"
	@echo "  lint           - Check Solidity formatting"
	@echo ""
	@echo "Analysis:"
	@echo "  gas            - Generate gas report"
	@echo "  sizes          - Show contract sizes"
	@echo ""
	@echo "Documentation:"
	@echo "  docs           - Generate Solidity documentation"
	@echo "  docs-bindings  - Generate and open Rust binding docs"
	@echo ""
	@echo "Cleanup:"
	@echo "  clean          - Remove all build artifacts"
	@echo "  clean-bindings - Remove only binding artifacts"
