//! Type-safe Rust bindings for Stoffel Solidity contracts.
//!
//! Generated by `forge bind` using the Alloy framework.

#![allow(clippy::all)]
#![allow(missing_docs)]
#![allow(rustdoc::all)]
#![allow(unused_imports)]
#![allow(unused_attributes)]

// Generated contract bindings
pub mod i_stoffel_access_control;
pub mod i_stoffel_coordinator;
pub mod i_stoffel_input_manager;
pub mod stoffel_access_control;
pub mod stoffel_coordinator;
pub mod stoffel_input_manager;

// Re-export main contract bindings
pub use stoffel_access_control::StoffelAccessControl;
pub use stoffel_coordinator::StoffelCoordinator;
pub use stoffel_input_manager::StoffelInputManager;

/// Interface bindings for Stoffel contracts.
pub mod interfaces {
    pub use crate::i_stoffel_access_control::IStoffelAccessControl;
    pub use crate::i_stoffel_coordinator::IStoffelCoordinator;
    pub use crate::i_stoffel_input_manager::IStoffelInputManager;
}

// Re-export commonly used types from alloy
pub use alloy::primitives::{Address, Bytes, FixedBytes, U256};
pub use alloy::sol_types::SolCall;
